### ISSUE TITLE
Strange map glitches on edited fit file

### ISSUE THREAD

**Issue by gfmoore** [karaul/fitplotter#2]
![image](https://user-images.githubusercontent.com/22768967/108633201-f0308880-746a-11eb-9213-97053b96e20e.png)

So what I did was edit a fit file because it had a speed glitch near the start. I edited it in Golden Cheetah and when displaying the changed file I got these vertical lines on the graph.

I've attached a before and after file.
[Downloads.zip](https://github.com/karaul/fitplotter/files/6018172/Downloads.zip)

I haven't debugged your code as I've got busy with something else, sorry.

**Comment by karaul** [comment]
Now fitplott is availbale online (alwways the lates version - I added different zoom control at the left bottom  )
https://karaul.github.io/fitplotter/
Could you please check your fit file with this online version ?

If there are the same glitches,  I will need the fit file with glitches for testing.

**Comment by karaul** [comment]
The original *.fit file is ok, hence, the effect is coming from the artificial editing. 

One does not need to edit spikes. There is droplist "zoom" at the bottom right corne (check whether you have latest version - if not, download latest index.html and srs/main.js ). Select "y axes" zoom, and then impose the desirable y-axis range with the spikes exculded.  In the  future version, I probably put an automatical spikes removal, it's not hard, but you can work already by using current functionality.

Also please check new fitplotter version online
https://karaul.github.io/fitplotter/
it's slower that a local versionm, but it has all the newest features.

**Comment by gfmoore** [comment]
>>> (did not notice *.fit files in downloads.zip)

Odd, I just downloaded it and saw the two files?

Tried the new version with my edited file same issue.
![image](https://user-images.githubusercontent.com/22768967/108634523-c9c21b80-7471-11eb-9190-c86d4bfbb92e.png)

Oh I see how the zoom works - cool.

**Comment by karaul** [comment]
Should I concentrate on the spike filtering or "y"-zoom selection is enough already? 

It is hard to imagine an effect of afterward editing, the simplet is just to ignore the edited fields, if they corrupt the structure, but then this  editing is meaningless

I worked a lot if of with the spikes in our physical experiments with real-time dynamics , and I know when the proper zoom eleminates the problem, no forced data correction is needed. It might be needed only for the final quaity-ready publication, which is always static (one could not change zoom), but rarely for analysis. In the course of the analysis one has to work with the true raw data rather then the edited data. One needs to have a very sharp understanding how the data were corrected to avoid self-cheating.

**Comment by gfmoore** [comment]
I don't know to be honest. Just for my own enjoyment I'm working on a D3 implementation where I just have a few narrow height strips one after the other. I don't have any issues with the edited data, but then again I'm not mapping it yet. Your plotter is much more sophisticated than mine.

I suspect that because I removed one record leaflet is now working with a discontinuity in the data set. I can imagine a few people wanting to edit their fit files as there are quite a few tools around that allow them to do this. Spike removal would be an interesting bit of code.

As for spikes, well this is the first time I've noticed it with my Garmin speed sensor. I'm not sure what happened. However, I am trying out a Powerpod 3 power meter and that seems to have some flakiness connecting to the sensors so maybe that caused an issue. I certainly didn't have a flawless connection at the start of my ride.

Also Karoo, despite my efforts and their protestations, don't seem to be a company that are that open to getting things done in a hurry. Pity as my first impressions of their computer is favourable, in particular I can see the screen. Its not as tiny as the Garmin 520 plus. But being based on a smartphone could be open to some really cool developments. From their responses and the fact that they map the route, plot elevation and do a few summary statistics, as well as have the option to download the fit file means they must have a database of the ride data. It would be trivial to offer your functionality and hack it to their corporate image.

In fact if I was to suggest a development of the server version it would be to retain all fit files in a (no sql json) database and allow selection and comparison analysis.

By the way what is HRE and how is it calculated? I'm a bit new to some of this fitness analysis stuff as I dont have any (fitness) :) 

Keep up the great work.

⁣Regards,

Gordon Moore
gm@gordonmoore.co.uk​

**Comment by karaul** [comment]
>  what is HRE and how is it calculated 

HRE = heart_rate * pace = number of heart beats per kilometer, it is explained here with example of the analysis
https://drive.google.com/file/d/17wK0y5p7rYlMRBogpZ9yicdnV191E1qx/view?usp=sharing

It is important for marathoners. Below image shows my HRE progress in 2020
![HRE_2020](https://user-images.githubusercontent.com/8741602/108636454-f97f1c80-748d-11eb-90b1-479e51f0eb54.jpg)

**Comment by gfmoore** [comment]
That's really interesting. 

⁣Regards,

Gordon Moore
gm@gordonmoore.co.uk​

**Comment by karaul** [comment]
_Also Karoo, despite my efforts and their protestations_

I have read their answer. I intended to reply too and offer my service, but in order to reply I needed to register, and I do not want. Anyway, if they are offerring  any sort of collaboration, I will be glad. This project has been started several years ago in matlab, then  with python, and finally with javascript.  In terms of thinking it is the matured project, and JS is just syntaxis, very  convenient and much faster than in python in terms GUI. No run-time libraries is needed, everything is inside the browser.

There are few more ideas I want to realize, so I continue to work on it

**Comment by karaul** [comment]
Filter to remove spikes is implemented. Tested with "Karoo-14th_ride-Feb-21-2021-123031.fit"

Below are raw data with spikes. The controls to remove spikes are  highlighted:
![in_order_to filter](https://user-images.githubusercontent.com/8741602/108646195-b9379280-74bd-11eb-9ff7-dc2b52483cd2.JPG)

(1) Select in the droplist  "Click in the legend" option "Apply filter ..." 
(2) Behind the  droplist,  set size of the filter more than  1 (at 0 no effect) 
(3) Click in the legend on the curve to be filtered, here,  "speed 21.02"
When everything is as should be, there will appear a filtered curve in addition to the  raw one. Other options will be restored, because the filtered operation is dangerous and quickly can make the plot dirty. So filter size will be set 0, and default "Hide/show .." option will be restored

Below is screenshot with the raw and filtered curves
![raw_and_filtered](https://user-images.githubusercontent.com/8741602/108646415-72966800-74be-11eb-9db5-87869db8b69c.JPG)

Check that in the droplist  "Click in the legend" is option "Hide/show..."  and click the original  raw curve with spike to hide it, the result is shown below
![filtered](https://user-images.githubusercontent.com/8741602/108646575-0c5e1500-74bf-11eb-977a-18414fe18414.JPG)

The filtered curve does not replace the raw one in fit-file dataset, i.e. if you click "Clean plot", the filtered curve disappear, the original raw remains in the y-axis drop list

It is unclear at the moment whether the filtered curve shoul be autmatically added to the the y-axis drop list. The fitplotter has no option to edit and save fit file.

It is an one-dimensional median filter implemented, see https://www.mathworks.com/help/signal/ref/medfilt1.html

**Comment by gfmoore** [comment]
I haven't had time yet to play with the filter, though it looks amazing. However, I can confirm that the glitches are to do with the edited file as on my own (very simple) plotter I get the same glitches with the simplest of maps and polylines. I think you can close this as it's not your software. I'll have a play with the filter later on. :)

**Comment by gfmoore** [comment]
I've just had a quick play and looked it up, the wikipedia entry is helpful: https://en.wikipedia.org/wiki/Median_filter 

Very clever. Am I right in saying that it does change the data slightly?

**Comment by karaul** [comment]
Yes, it changes just slightly rather than drastically as with [Moving_average](https://en.wikipedia.org/wiki/Moving_average), For completeness it is necessarry to have both filters. To implement the moving average filter is simpler as the median one .

PS: I did not know about the Wikiedia paper about the median  :)

**Comment by gfmoore** [comment]
Another approach I've just tried with my very basic app, is if I find any value greater than 150 ignore it when I scan through the fit object to create my data set for use with D3. (I'm assuming that I'll never go faster than 150km/h even if I fell off a mountain!!! :) The value it discovered was 237 at 1.39351km  Defo a spike! I might have fallen into the canal I was riding alongside! ;)

**Comment by karaul** [comment]
_any value greater than 150 ignore_

it's a naive approach to set an allowed range :),  it depends always on the parameter under the consideration  and leads to nowhere, because  there might be always candidates running away.

**Comment by gfmoore** [comment]
Fair point. Do you want me to close this, I'm not sure of the protocol for that?

**Comment by karaul** [comment]
I do not either, I close :) Probably  I should open "Discussion" for general themes - I have seen on option in the settings, but before I need to read manual to understand what is it.

Thank you for the testing.
