### ISSUE TITLE
What is "Median filter size" and "Average moving size" doing?

### ISSUE THREAD

**Issue by rucksman** [karaul/fitplotter#4]
First of all thank you for this project. As I am new to Garmin devices, I am very glad to have a tool running on my own server instead of Garmins servers.

I know that you are not working on fitplotter anymore, but I hope nevertheless to get some information from you: I am currently adapting fitplotter and fitalyser to my needs and stumbled upon "Median filter size" and "Average moving size". To be honest: I have no clue what both of them are doing. I did play around with the values but saw no differences in the plot area nor in the map. I did some  superficial investigation in main.js, but this did not help me either, Can you please briefly explain what the two variables do? Thank you!

**Comment by karaul** [comment]
> stumbled upon "Median filter size" and "Average moving size". 

These are to smooth noisy data.  

 "Median filter size" is explained at https://en.wikipedia.org/wiki/Median_filter section "Worked one-dimensional example"

"Average moving size" is explained at https://en.wikipedia.org/wiki/Moving_average section "Simple moving average"

If the inintial data are not noisy, these filters have no effects. Nowadays, it's the case because a smooth algorithm might already be implented into the watch hardware, howere, ten years ago, with the first Garmin watches, one typically  had an issiue with noisy data

**Comment by rucksman** [comment]
Thanks for the very quick reply!
